language: php

php:
  - 5.4
  - 5.5
  # - hhvm

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
   - phpunit --coverage-clover docs/phpunit/clover.xml

install:
   - composer require mikey179/vfsStream:1.2.0

after_script:
 - php vendor/bin/coveralls -v
